### ISSUE TITLE
Improper handling of install name for shared library on OS X

### ISSUE THREAD

**Issue by elfprince13** [Pivotal-Data-Attic/pivotalrd-libhdfs3#46]
I am working on a project that has libhdfs3 as a submodule in our git repo. Since we want to keep the build process contained in a single (user-owned) directory tree, we configure with `cmake -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/usr`. However, after running `make && make install`, I then find the following incorrect behavior when I run otool.

```
[thomas@Mithlond] libhdfs3-cmake $ otool -D usr/lib/libhdfs3.dylib
usr/lib/libhdfs3.dylib:
libhdfs3.1.dylib
```

Note that since the install name is incorrectly set, linking against this copy of the library, even by absolute path, will produce a binary that can't find libhdfs3.dylib without manually altering LD_LIBRARY_PATH.

**Comment by kdunn-pivotal** [comment]
@elfprince13  - Apologies for the *very* delayed response. The development team managing this codebase is also responsible for [Apache HAWQ](http://hawq.incubator.apache.org/) (incubating) and trying to get the first release out the door. As a result, this repo has been unintentionally neglected and recently turned read-only. 

This code was birthed from HAWQ and will be [merged](https://issues.apache.org/jira/browse/HAWQ-1046) back into into that project (now that it is open source as well); [mailing lists](http://mail-archives.apache.org/mod_mbox/incubator-hawq-dev/), pull requests, [issues](https://issues.apache.org/jira/browse/HAWQ) and releases related to libhdfs3 will be there. The plan is to provide [tarball releases](https://issues.apache.org/jira/browse/HAWQ-1058) of this code separate from the larger HAWQ project until it can be relocated into a dedicated repo again (down the road) - see [HAWQ-1059](https://issues.apache.org/jira/browse/HAWQ-1059).

Again, thank you for the contribution and patience while we sort out these logistics. 

If this issue/feature is still active, please respond otherwise it will be closed.

**Comment by elfprince13** [comment]
Yep, still active. My current work-around is adding

```
if [[ "$OS_UNAME" == "Darwin" ]]; then
	install_name_tool -id `pwd`/usr/lib/libhdfs3.1.dylib `pwd`/usr/lib/libhdfs3.1.dylib
fi
```

into a bash script that runs as a wrapper around the build task, but I'd appreciate having the official CMake files configured correctly.

**Comment by kdunn-pivotal** [comment]
Issue tracking moved here to [HAWQ-1066](https://issues.apache.org/jira/browse/HAWQ-1066).

Vote to close the issue here.

**Comment by elfprince13** [comment]
Sounds good, thanks!
